import React, { use, useEffect, useRef, useState } from "react";
import { useParams } from "react-router";
import useAxiosSecure from "../hooks/useAxiosSecure";
import { AuthContext } from "../Provider/AuthContext";

const BilDetails = () => {
  const { id: billId } = useParams();
  const axiosSecure = useAxiosSecure();
  const [bill, setBill] = useState(null);
  const [loading, setLoading] = useState(true);
  const bilModalRef = useRef(null);
  const { user } = use(AuthContext);
  const [updataBil, serUpdateBil] = useState([]);

  useEffect(() => {
    if (billId) {
      setLoading(true);

      axiosSecure
        .get(`/bills/${billId}`)
        .then((response) => {
          setBill(response.data);
          console.log(response.data);
          setLoading(false);
        })
        .catch((error) => {
          console.error("Fetch failed:", error);
          setLoading(false);
        });
    }
  }, [axiosSecure, billId]);

  if (loading) {
    return <div className="text-center py-8">Loading Bill Details...</div>;
  }
  if (!bill) {
    return (
      <div className="text-center py-8 text-red-500">
        Bill not found or access denied.
      </div>
    );
  }

  const handleBillModalOpen = () => {
    bilModalRef.current.showModal();
  };
  const handleBillSubmit = (e) => {
    e.preventDefault();

    // 1. Extract values from form fields
    const username = e.target.username.value;
    const email = e.target.email.value;
    const phone = e.target.phone.value;
    const address = e.target.address.value;
    const amount = parseFloat(e.target.amount.value); // Convert amount to a number
    const date = e.target.date.value;

    // 2. Structure the data object to match your required format
    const newBillData = {
      // Note: billsId is typically generated by the backend database
      username: username,
      Phone: phone, // Note: Ensure this matches the backend field name
      Address: address,
      email: email,
      amount: amount,
      date: date,
      // Add any other necessary default fields (e.g., a status)
      status: "active", // Example status field
    };

    console.log("Submitting new bill data:", newBillData);

    // 3. Send the data to the backend API endpoint
    // Use a suitable endpoint like '/bills' for creating a new resource
    axiosSecure
      .post("/myBills", newBillData)
      .then((res) => {
        console.log("New Bill created successfully:", res.data);
        // Optional: Show success toast/alert, clear the form, or redirect the user
      })
      .catch((error) => {
        console.error("Error creating new bill:", error);
        // Optional: Show error message
      });
  };

  return (
    <div>
      <h1>{bill.title}</h1>
      <button onClick={handleBillModalOpen} className="btn btn-primary">
        I want to submit this bill
      </button>

      <dialog ref={bilModalRef} className="modal modal-bottom sm:modal-middle">
        <div className="modal-box">
          <h3 className="font-bold text-lg">Give the best offer!</h3>
          <p className="py-4">Offer something seller can not resist</p>
          <form onSubmit={handleBillSubmit}>
            <fieldset className="fieldset grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Username (Pre-filled and Read-only) */}
              <div className="col-span-1">
                <label className="label">Username</label>
                <input
                  type="text"
                  name="username"
                  className="input"
                  readOnly
                  defaultValue={user?.displayName || "N/A"}
                />
              </div>

              {/* Email (Pre-filled and Read-only) */}
              <div className="col-span-1">
                <label className="label">Email</label>
                <input
                  type="email"
                  className="input"
                  name="email"
                  readOnly
                  defaultValue={user?.email || "N/A"}
                />
              </div>

              {/* Phone */}
              <div className="col-span-1">
                <label className="label">Phone</label>
                <input
                  type="tel"
                  name="phone"
                  className="input"
                  placeholder="e.g., 017XXXXXXXX"
                  required
                />
              </div>

              {/* Address */}
              <div className="col-span-1">
                <label className="label">Address</label>
                <input
                  type="text"
                  name="address"
                  className="input"
                  placeholder="e.g., Dhaka"
                  required
                />
              </div>

              {/* Amount */}
              <div className="col-span-1">
                <label className="label">Amount</label>
                <input
                  type="number"
                  name="amount"
                  className="input"
                  placeholder="e.g., 260"
                  min="1"
                  step="0.01"
                  required
                />
              </div>

              {/* Date */}
              <div className="col-span-1">
                <label className="label">Date</label>
                <input type="date" name="date" className="input" required />
              </div>

              {/* Submit Button */}
              <div className="col-span-full mt-4">
                <button type="submit" className="btn btn-primary w-full">
                  Submit New Bill
                </button>
              </div>
            </fieldset>
          </form>

          <div className="modal-action">
            <form method="dialog">
              {/* if there is a button in form, it will close the modal */}
              <button className="btn">Cancel</button>
            </form>
          </div>
        </div>
      </dialog>
    </div>
  );
};
export default BilDetails;
